import Image from "next/image";
import Link from "next/link";
import { featuredProjects, galleryItems, impact, partners } from "@/lib/site-data";
import { ArrowUpRight } from "@/components/ui/icons";
import { Reveal } from "./reveal";

export function HomePage() {
  return <main>
    <section className="hero relative flex min-h-[760px] items-end overflow-hidden bg-ink text-cream lg:min-h-screen">
      <Image src="/images/hero-arta-in-dar.png" alt="Trei generații creează împreună, la o masă cu flori, ceramică și fotografii vechi" fill priority sizes="100vw" className="object-cover object-[68%_center]" />
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(45,36,31,.86)_0%,rgba(45,36,31,.47)_43%,rgba(45,36,31,.05)_78%),linear-gradient(0deg,rgba(45,36,31,.65),transparent_55%)]" />
      <div className="paper-noise absolute inset-0 opacity-30 mix-blend-soft-light" />
      <div className="shell relative z-10 pb-16 pt-36 lg:pb-20"><div className="max-w-4xl">
        <p className="mb-6 flex items-center gap-3 text-[10px] font-bold uppercase tracking-[.32em] text-gold"><span className="h-px w-10 bg-gold" />Asociație culturală · România</p>
        <h1 className="font-display text-[clamp(4.3rem,11vw,10.8rem)] leading-[.76] tracking-[-.065em]">Arta ne<br /><span className="ml-[.12em] italic text-gold">unește.</span></h1>
        <div className="mt-10 flex max-w-2xl flex-col gap-7 border-l border-cream/35 pl-5 sm:flex-row sm:items-end sm:justify-between"><p className="max-w-md text-base leading-relaxed text-cream/80 sm:text-lg">Dăm viață locurilor prin artă, patrimoniu și oameni care aleg să construiască împreună.</p><Link href="/despre-noi" className="group inline-flex shrink-0 items-center gap-3 text-xs font-bold uppercase tracking-[.18em]">Povestea noastră <span className="grid size-11 place-items-center rounded-full bg-terracotta transition-transform group-hover:rotate-45"><ArrowUpRight className="size-5" /></span></Link></div>
      </div></div>
    </section>

    <section className="relative overflow-hidden py-24 lg:py-36"><span className="absolute -right-10 top-5 select-none font-display text-[16rem] leading-none text-terracotta/[.045]">dar</span><div className="shell grid gap-14 lg:grid-cols-[.8fr_1.2fr] lg:gap-24"><Reveal><p className="eyebrow text-terracotta">Despre Arta în Dar</p><div className="mt-10 flex items-center gap-4"><span className="font-display text-7xl italic text-gold">A</span><span className="h-px flex-1 bg-ink/20" /></div></Reveal><Reveal delay={.1}><h2 className="heading-lg">Arta devine cu adevărat valoroasă atunci când <em>circulă</em> între oameni.</h2><div className="mt-10 grid gap-8 border-t border-ink/15 pt-8 sm:grid-cols-2"><p className="body-copy">Suntem o comunitate de artiști, voluntari și oameni ai locului. Creăm contexte în care cultura nu se privește de la distanță, ci se trăiește.</p><div><p className="body-copy">Recuperăm povești, activăm spații și aducem la aceeași masă generații diferite.</p><Link href="/despre-noi" className="text-link mt-6">Cunoaște-ne mai bine <ArrowUpRight className="size-4" /></Link></div></div></Reveal></div></section>

    <section className="canvas-section py-24 lg:py-32"><div className="shell"><Reveal className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow text-gold">Proiecte cu urme</p><h2 className="heading-xl mt-5">Idei care prind<br /><em>rădăcini.</em></h2></div><Link className="text-link" href="/pelerinaj-7-capele">Descoperă proiectul emblematic <ArrowUpRight className="size-4" /></Link></Reveal><div className="mt-14 grid gap-5 lg:grid-cols-3">{featuredProjects.map((project, index) => <Reveal key={project.title} delay={index * .08}><Link href={project.href} className={`project-card project-card--${project.color} group`}><span className="project-card__number">{project.number}</span><div className="relative z-10 mt-auto"><p className="text-[9px] font-bold uppercase tracking-[.22em] opacity-65">{project.category}</p><h3 className="mt-3 font-display text-4xl leading-none">{project.title}</h3><p className="mt-5 text-sm leading-relaxed opacity-70">{project.description}</p><span className="mt-7 inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em]">Descoperă <ArrowUpRight className="size-4 transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></span></div></Link></Reveal>)}</div></div></section>

    <section className="bg-olive py-24 text-cream lg:py-32"><div className="shell"><Reveal><p className="eyebrow text-gold">Impactul nostru</p><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{impact.map((item) => <div key={item.label} className="border-t border-cream/25 pt-6"><strong className="block font-display text-7xl font-normal tracking-tight text-gold lg:text-8xl">{item.value}</strong><p className="mt-3 max-w-[11rem] text-sm leading-snug text-cream/70">{item.label}</p></div>)}</div></Reveal></div></section>

    <section className="py-24 lg:py-36"><div className="shell"><Reveal className="text-center"><p className="eyebrow text-terracotta">Fragmente de viață</p><h2 className="heading-xl mt-5">O galerie care <em>respiră.</em></h2></Reveal><div className="gallery-grid mt-14">{galleryItems.map((item, i) => <Reveal className={`gallery-tile gallery-tile--${i + 1}`} key={item.label} delay={i * .06}><div className={`gallery-art gallery-art--${item.tone}`}><span className="gallery-art__shape" /><span className="gallery-art__line" /></div><p className="mt-3 flex items-center justify-between font-display text-xl italic">{item.label}<span className="font-sans text-[9px] not-italic tracking-widest">0{i + 1}</span></p></Reveal>)}</div></div></section>

    <section className="overflow-hidden bg-terracotta text-cream"><div className="shell grid lg:grid-cols-2"><Reveal className="cta-panel border-b border-cream/20 lg:border-b-0 lg:border-r lg:pr-16" ><p className="eyebrow text-gold">Intră în poveste</p><h2 className="mt-5 font-display text-6xl leading-[.9] md:text-7xl">Dăruiește<br /><em>timp.</em></h2><p className="mt-7 max-w-sm text-cream/75">Uneori, cea mai importantă resursă este un om care spune „vin și eu”.</p><Link href="/doneaza-fii-voluntar" className="button-light mt-9 w-fit">Devino voluntar <ArrowUpRight className="size-4" /></Link></Reveal><Reveal delay={.1} className="cta-panel lg:pl-16"><p className="eyebrow text-gold">Susține un proiect</p><h2 className="mt-5 font-display text-6xl leading-[.9] md:text-7xl">Dăruiește<br /><em>posibilitate.</em></h2><p className="mt-7 max-w-sm text-cream/75">Fiecare contribuție se transformă în materiale, întâlniri și locuri readuse la viață.</p><Link href="/doneaza-fii-voluntar#doneaza" className="button-light mt-9 w-fit">Donează <ArrowUpRight className="size-4" /></Link></Reveal></div></section>

    <section className="py-20"><div className="shell"><Reveal><p className="text-center text-[10px] font-bold uppercase tracking-[.26em] text-ink/45">Creștem prin încredere și colaborare</p><div className="mt-9 grid grid-cols-2 border-l border-t border-ink/15 lg:grid-cols-4">{partners.map(partner => <div key={partner} className="grid min-h-28 place-items-center border-b border-r border-ink/15 px-4 text-center font-display text-lg text-ink/60">{partner}</div>)}</div></Reveal></div></section>
  </main>;
}
